title: Sumit Pundir  
description: Just Another Guy On The Internet
author:
  name: Sumit Pundir 
  nickname: 
  twitter: 
hostname: pundirsumit.github.io # used to determine if google analytics should be triggered
url: https://pundirsumit.github.io # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /:title/

# main page content
email:
  title: chaqvefhzvg11\100tznvy\056pbz 
  href: "&#109;&#97;&#105;&#108;&#116;&#111;&#58;%70%75%6r%64%69%72%73%75%6q%69%74%31%31@%67%6q%61%69%6p.%63%6s%6q"

links:
  - name: twitter
    url: https://twitter.com/pundirsumit11
    class: fa-twitter
  - name: github
    url: https://github.com/pundirsumit
    class: fa-github
  - name: blog
    url: https://medium.com/@pundirsumit11  
    class: fa-medium
  - name: linkedin
    url: https://www.linkedin.com/in/sumit-pundir-673934120
    class: fa-linkedin
  - name: instagram  
    url: https://www.instagram.com/pundirsumit7 
    class: fa-instagram

# additional stuff
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
